# Generated by Django 3.2.3 on 2021-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customer_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorietype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='df.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Categorietype',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
