# Generated by Django 3.2.3 on 2021-06-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210611_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shop_name',
        ),
    ]
